/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tiidea.view;

import br.com.tiidea.dao.UsuarioDao;
import br.com.tiidea.classe.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author 801501279
 */
public class FTelaInicial extends javax.swing.JFrame {

    
    
    /**
     * Creates new form fTelaDeInicial
     */
    public FTelaInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbNomeUsuario = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        edNomeUsuario = new javax.swing.JTextField();
        btEntrar = new javax.swing.JButton();
        btCriarConta = new javax.swing.JButton();
        lbTituloCadastroUsuario = new javax.swing.JLabel();
        edSenha = new javax.swing.JPasswordField();
        btFechar = new javax.swing.JButton();
        btEsqueciSenha = new javax.swing.JButton();
        lbPlanodeFundo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNomeUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomeUsuario.setText("Nome de usuario:");
        jPanel1.add(lbNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 500, -1));

        lbSenha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbSenha.setText("Senha:");
        jPanel1.add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));
        jPanel1.add(edNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 282, 31));

        btEntrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.setMaximumSize(new java.awt.Dimension(143, 25));
        btEntrar.setMinimumSize(new java.awt.Dimension(143, 25));
        btEntrar.setPreferredSize(new java.awt.Dimension(143, 25));
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 280, -1));

        btCriarConta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btCriarConta.setText("Criar uma conta");
        btCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarContaActionPerformed(evt);
            }
        });
        jPanel1.add(btCriarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 280, -1));

        lbTituloCadastroUsuario.setFont(new java.awt.Font("Sandoval", 1, 48)); // NOI18N
        lbTituloCadastroUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/iconfinder_BT_c3tool_905663.png"))); // NOI18N
        lbTituloCadastroUsuario.setText("MY CAR");
        lbTituloCadastroUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lbTituloCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 160));
        jPanel1.add(edSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 280, 31));

        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/iconfinder_icon-close-round_211651.png"))); // NOI18N
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        jPanel1.add(btFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        btEsqueciSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btEsqueciSenha.setText("Esqueci a senha");
        jPanel1.add(btEsqueciSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 280, -1));

        lbPlanodeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/380567.png"))); // NOI18N
        jPanel1.add(lbPlanodeFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarContaActionPerformed
         fTelaCadastroUsuario Telacadastro = new fTelaCadastroUsuario();
         FTelaInicial TelaInicial = new FTelaInicial();
         Telacadastro.setVisible(true);
         dispose();
         
         
         
    }//GEN-LAST:event_btCriarContaActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
       UsuarioDao dao = new UsuarioDao();
       
       if(dao.checkLogin(edNomeUsuario.getText(), edSenha.getText())){
           new fTelaUsuario().setVisible(true);
           
           Usuario usuario = new Usuario();
           usuario.setIdUser(dao.getIdUser);
           
           this.dispose();
       }else{
           JOptionPane.showMessageDialog(null, "Login ou Senha incorreta!");
       }
    }//GEN-LAST:event_btEntrarActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btFecharActionPerformed

    /**
     * @param args the command line arguments
     */
      
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriarConta;
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btEsqueciSenha;
    private javax.swing.JButton btFechar;
    private javax.swing.JTextField edNomeUsuario;
    private javax.swing.JPasswordField edSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbPlanodeFundo;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTituloCadastroUsuario;
    // End of variables declaration//GEN-END:variables
}
