/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tiidea.view;

import br.com.tiidea.classe.Usuario;
import br.com.tiidea.classe.Veiculo;
import br.com.tiidea.dao.VeiculoDao;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 801501279
 */
public class fTelaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form fTelaUsuario
     */
    public fTelaUsuario() {
         initComponents();
         setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTituloCadastroUsuario = new javax.swing.JLabel();
        lbNomeUsuario = new javax.swing.JLabel();
        lbCpfUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabelaVeiculos = new javax.swing.JTable();
        lbVeiculo = new javax.swing.JLabel();
        btIncluir = new javax.swing.JButton();
        btAlterarCarro = new javax.swing.JButton();
        lbEmailUsuario1 = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloCadastroUsuario.setFont(new java.awt.Font("Sandoval", 1, 48)); // NOI18N
        lbTituloCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/iconfinder_BT_c3tool_905663.png"))); // NOI18N
        lbTituloCadastroUsuario.setText("PERFIL");
        jPanel1.add(lbTituloCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 317, -1));

        lbNomeUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbNomeUsuario.setText("Nome");
        jPanel1.add(lbNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lbCpfUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbCpfUsuario.setText("CPF");
        jPanel1.add(lbCpfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        tbTabelaVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "MARCA", "PLACA", "MODELO", "ANO", "CUSTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbTabelaVeiculos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 450, 70));

        lbVeiculo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbVeiculo.setText("VEICULOS");
        jPanel1.add(lbVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        btIncluir.setBackground(new java.awt.Color(255, 255, 255));
        btIncluir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btIncluir.setText("INCLUIR");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });
        jPanel1.add(btIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 170, 50));

        btAlterarCarro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btAlterarCarro.setText("EDITAR");
        btAlterarCarro.setPreferredSize(new java.awt.Dimension(141, 37));
        jPanel1.add(btAlterarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 140, 50));

        lbEmailUsuario1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbEmailUsuario1.setText("Email");
        jPanel1.add(lbEmailUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        btExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btExcluir.setText("EXCLUIR");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/380567.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, 0, 920, 500));

        jMenu2.setText("jMenu2");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        fTelaIncluirVeiculo TelaIncluir = new fTelaIncluirVeiculo();
        TelaIncluir.setVisible(true);
        dispose();     

    }//GEN-LAST:event_btIncluirActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fTelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fTelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarCarro;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCpfUsuario;
    private javax.swing.JLabel lbEmailUsuario1;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbTituloCadastroUsuario;
    private javax.swing.JLabel lbVeiculo;
    private javax.swing.JTable tbTabelaVeiculos;
    // End of variables declaration//GEN-END:variables
}
