/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tiidea.view;

/**
 *
 * @author 801501279
 */
public class fTelaAlterarPerfil extends javax.swing.JFrame {

    /**
     * Creates new form fTelaAlterarPerfil
     */
    public fTelaAlterarPerfil() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTituloCadastroUsuario = new javax.swing.JLabel();
        btAlterarPerfil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbNomeUsuario = new javax.swing.JLabel();
        edNomeUsuarioAlterar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbSenhaUsuario = new javax.swing.JLabel();
        fedSenha = new javax.swing.JPasswordField();
        lbConfirmSenha = new javax.swing.JLabel();
        fedConfirmSenha = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        lbEmailUsuario = new javax.swing.JLabel();
        edSenhaAlterar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lbCepUsuario = new javax.swing.JLabel();
        lbFoneUsuario = new javax.swing.JLabel();
        fedCep = new javax.swing.JFormattedTextField();
        fedTelefone = new javax.swing.JFormattedTextField();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloCadastroUsuario.setFont(new java.awt.Font("Sandoval", 1, 48)); // NOI18N
        lbTituloCadastroUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/iconfinder_BT_c3tool_905663.png"))); // NOI18N
        lbTituloCadastroUsuario.setText("ATERAR PERFIL");
        jPanel1.add(lbTituloCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 590, -1));

        btAlterarPerfil.setBackground(new java.awt.Color(255, 255, 255));
        btAlterarPerfil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btAlterarPerfil.setText("Alterar");
        jPanel1.add(btAlterarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 470, 550, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Login"));

        lbNomeUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNomeUsuario.setText("Login:");

        edNomeUsuarioAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNomeUsuarioAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edNomeUsuarioAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeUsuario)
                    .addComponent(edNomeUsuarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 550, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Senha"));

        lbSenhaUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbSenhaUsuario.setText("Senha:");

        lbConfirmSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbConfirmSenha.setText("Confirmar:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbSenhaUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fedSenha))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbConfirmSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fedConfirmSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenhaUsuario)
                    .addComponent(fedSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConfirmSenha)
                    .addComponent(fedConfirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 550, 100));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Email"));

        lbEmailUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbEmailUsuario.setText("Email:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEmailUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edSenhaAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmailUsuario)
                    .addComponent(edSenhaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 550, 60));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Informações Pessoais"));

        lbCepUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbCepUsuario.setText("CEP:");

        lbFoneUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbFoneUsuario.setText("Telefone:");

        try {
            fedCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fedCep.setPreferredSize(new java.awt.Dimension(55, 20));

        try {
            fedTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fedTelefone.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCepUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fedCep, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbFoneUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fedTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCepUsuario)
                    .addComponent(fedCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFoneUsuario)
                    .addComponent(fedTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 550, 60));

        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/380567.png"))); // NOI18N
        jPanel1.add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edNomeUsuarioAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNomeUsuarioAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNomeUsuarioAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fTelaAlterarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fTelaAlterarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fTelaAlterarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fTelaAlterarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fTelaAlterarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarPerfil;
    private javax.swing.JTextField edNomeUsuarioAlterar;
    private javax.swing.JTextField edSenhaAlterar;
    private javax.swing.JFormattedTextField fedCep;
    private javax.swing.JPasswordField fedConfirmSenha;
    private javax.swing.JPasswordField fedSenha;
    private javax.swing.JFormattedTextField fedTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbCepUsuario;
    private javax.swing.JLabel lbConfirmSenha;
    private javax.swing.JLabel lbEmailUsuario;
    private javax.swing.JLabel lbFoneUsuario;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbSenhaUsuario;
    private javax.swing.JLabel lbTituloCadastroUsuario;
    // End of variables declaration//GEN-END:variables
}
