/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tiidea.view;

 
import br.com.tiidea.classe.Usuario;
import br.com.tiidea.classe.Veiculo;
import br.com.tiidea.dao.UsuarioDao;
import br.com.tiidea.dao.VeiculoDao;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class fTelaIncluirVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form fTelaIncluirVeiculo
     */
    public fTelaIncluirVeiculo() {
        initComponents();
        String[] marca = { "Toyota","Volkswagen","Ford","Nissan","Honda","Hyundai","Chevrolet","Kia","Mercedes-Benz","Renault","BMW",
            "Peugeot","Audi","Maruti","Mazda","Jeep","Fiat","Suzuki","Geely","Buick","Changan" };
        setLocationRelativeTo(null);
         UsuarioDao dao = new UsuarioDao();
        JComboBox listaMarca = new JComboBox(marca);
        listaMarca.setSelectedIndex(20);
        listaMarca.addActionListener(listaMarca);
        for(Usuario p: dao.read()){
            /*cbcliente.addItem(p.getIdUser());*/
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTituloCadastroUsuario = new javax.swing.JLabel();
        btCadastrarUsuario = new javax.swing.JButton();
        btVoltarTelaCadasUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbLoginUsuario = new javax.swing.JLabel();
        lbEmailUsuario1 = new javax.swing.JLabel();
        lbEmailUsuario = new javax.swing.JLabel();
        lbNomeUsuario = new javax.swing.JLabel();
        lbFoneUsuario = new javax.swing.JLabel();
        cbMarca = new javax.swing.JComboBox<>();
        edModelo = new javax.swing.JTextField();
        jftAno = new javax.swing.JFormattedTextField();
        jftPlacaAntiga = new javax.swing.JFormattedTextField();
        jftPlacaNova = new javax.swing.JFormattedTextField();
        cbAdaptado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloCadastroUsuario.setFont(new java.awt.Font("Sandoval", 1, 48)); // NOI18N
        lbTituloCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/iconfinder_BT_c3tool_905663.png"))); // NOI18N
        lbTituloCadastroUsuario.setText("INCLUIR");
        jPanel1.add(lbTituloCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 426, 120));

        btCadastrarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btCadastrarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCadastrarUsuario.setText("INCLUIR VEICULO");
        btCadastrarUsuario.setPreferredSize(new java.awt.Dimension(240, 37));
        btCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btCadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        btVoltarTelaCadasUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btVoltarTelaCadasUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltarTelaCadasUsuario.setText("Voltar");
        btVoltarTelaCadasUsuario.setPreferredSize(new java.awt.Dimension(240, 37));
        btVoltarTelaCadasUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarTelaCadasUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btVoltarTelaCadasUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Veículo"));

        lbLoginUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbLoginUsuario.setText("Marca:");

        lbEmailUsuario1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbEmailUsuario1.setText("Modelo:");

        lbEmailUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbEmailUsuario.setText("Ano:");

        lbNomeUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNomeUsuario.setText("Placa:");

        lbFoneUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbFoneUsuario.setText("Adaptado:");

        cbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "Toyota", "Volkswagen", "Ford", "Nissan", "Honda", "Hyundai", "Chevrolet", "Kia", "Mercedes-Benz", "Renault", "BMW", "Peugeot", "Audi", "Maruti", "Mazda", "Jeep", "Fiat", "Suzuki", "Geely", "Buick", "Changan" }));

        try {
            jftAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftAnoActionPerformed(evt);
            }
        });

        try {
            jftPlacaAntiga.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftPlacaAntiga.setText("ANT-    ");

        try {
            jftPlacaNova.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***#*##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftPlacaNova.setText("NOV    ");
        jftPlacaNova.setPreferredSize(new java.awt.Dimension(56, 20));

        cbAdaptado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selcione", "Sim", "Não" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbLoginUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbEmailUsuario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbEmailUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftAno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbNomeUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftPlacaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftPlacaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbFoneUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAdaptado, 0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLoginUsuario)
                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmailUsuario1)
                    .addComponent(edModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbEmailUsuario)
                        .addComponent(jftAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNomeUsuario)
                        .addComponent(jftPlacaNova, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jftPlacaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFoneUsuario)
                            .addComponent(cbAdaptado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 500, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/380567.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarUsuarioActionPerformed
        
        
        Veiculo u = new Veiculo();
        VeiculoDao dao = new VeiculoDao();
        
        Usuario usuario = new Usuario();
       /*usuario.setIdUser((int)cbcliente.getSelectedItem());*/  
        
        u.setFkidcliente(usuario);
         /*usuario.setIdUser((int)cbcliente.getSelectedItem());*/  
        u.setPlateCar(jftPlacaNova.getText());
        u.setPlateCar(jftPlacaAntiga.getText());
        u.setBrandCar(cbMarca.getItemAt(WIDTH));
        u.setModelCar(edModelo.getText());
        u.setYearCar(Integer.parseInt(jftAno.getText()));
        u.setAdapted(cbAdaptado.getItemAt(WIDTH)); 
      //   JOptionPane.showMessageDialog(null,cbcliente.getSelectedItem());
        
        
        dao.create(u);
        
        
        fTelaUsuario TelaUsuario = new fTelaUsuario();
        TelaUsuario.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_btCadastrarUsuarioActionPerformed

    private void btVoltarTelaCadasUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarTelaCadasUsuarioActionPerformed
        fTelaUsuario TelaUsuario = new fTelaUsuario();
        TelaUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarTelaCadasUsuarioActionPerformed

    private void jftAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftAnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fTelaIncluirVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fTelaIncluirVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fTelaIncluirVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fTelaIncluirVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fTelaIncluirVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarUsuario;
    private javax.swing.JButton btVoltarTelaCadasUsuario;
    private javax.swing.JComboBox<String> cbAdaptado;
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JTextField edModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField jftAno;
    private javax.swing.JFormattedTextField jftPlacaAntiga;
    private javax.swing.JFormattedTextField jftPlacaNova;
    private javax.swing.JLabel lbEmailUsuario;
    private javax.swing.JLabel lbEmailUsuario1;
    private javax.swing.JLabel lbFoneUsuario;
    private javax.swing.JLabel lbLoginUsuario;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbTituloCadastroUsuario;
    // End of variables declaration//GEN-END:variables
}
