/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tiidea.view;

import br.com.tiidea.classe.Usuario;
import br.com.tiidea.dao.UsuarioDao;
import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 801501279
 */
public class fTelaCadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form fTelaCadastro
     */
    public fTelaCadastroUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpButtonsSexo = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbTituloCadastroUsuario = new javax.swing.JLabel();
        btCadastrarUsuario = new javax.swing.JButton();
        btVoltarTelaCadasUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        edLoginUsuario = new javax.swing.JTextField();
        lbLoginUsuario = new javax.swing.JLabel();
        edEmailUsuario = new javax.swing.JTextField();
        lbEmailUsuario = new javax.swing.JLabel();
        edSenhaUsuario = new javax.swing.JPasswordField();
        lbSenhaUsuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbDtNascimentoUsuario = new javax.swing.JLabel();
        jftDatadeNascimento = new javax.swing.JFormattedTextField();
        lbCepUsuario = new javax.swing.JLabel();
        jftCEP = new javax.swing.JFormattedTextField();
        lbCpfUsuario = new javax.swing.JLabel();
        jftCPF = new javax.swing.JFormattedTextField();
        lbFoneUsuario = new javax.swing.JLabel();
        jftTelefone = new javax.swing.JFormattedTextField();
        lbNomeCompleto = new javax.swing.JLabel();
        edNomeCompleto = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        cbGenderUser = new javax.swing.JComboBox<>();
        lbEstado = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        edEstado = new javax.swing.JTextField();
        edCidade = new javax.swing.JTextField();
        edEndereco = new javax.swing.JTextField();
        edBairro = new javax.swing.JTextField();
        lbNumero = new javax.swing.JLabel();
        lbComplemento = new javax.swing.JLabel();
        edNumero = new javax.swing.JTextField();
        edComplemento = new javax.swing.JTextField();
        btProcurar = new javax.swing.JButton();
        lbPlanodeFundo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloCadastroUsuario.setFont(new java.awt.Font("Sandoval", 1, 48)); // NOI18N
        lbTituloCadastroUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/iconfinder_BT_c3tool_905663.png"))); // NOI18N
        lbTituloCadastroUsuario.setText("CADASTRO");
        jPanel1.add(lbTituloCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 120));

        btCadastrarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btCadastrarUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btCadastrarUsuario.setText("CADASTRAR");
        btCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btCadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, -1, -1));

        btVoltarTelaCadasUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btVoltarTelaCadasUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btVoltarTelaCadasUsuario.setText("Voltar");
        btVoltarTelaCadasUsuario.setPreferredSize(new java.awt.Dimension(179, 37));
        btVoltarTelaCadasUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarTelaCadasUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btVoltarTelaCadasUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Login"));

        edLoginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edLoginUsuarioActionPerformed(evt);
            }
        });

        lbLoginUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbLoginUsuario.setText("Login:");

        edEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edEmailUsuarioActionPerformed(evt);
            }
        });

        lbEmailUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbEmailUsuario.setText("Email:");

        edSenhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edSenhaUsuarioActionPerformed(evt);
            }
        });

        lbSenhaUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbSenhaUsuario.setText("Senha:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSenhaUsuario)
                    .addComponent(lbLoginUsuario)
                    .addComponent(lbEmailUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLoginUsuario)
                    .addComponent(edLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmailUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSenhaUsuario))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 630, 170));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        lbDtNascimentoUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbDtNascimentoUsuario.setText("Data de nascimento:");

        try {
            jftDatadeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbCepUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbCepUsuario.setText("CEP:");

        try {
            jftCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftCEPActionPerformed(evt);
            }
        });

        lbCpfUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbCpfUsuario.setText("CPF:");

        try {
            jftCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbFoneUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbFoneUsuario.setText("Telefone:");

        try {
            jftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbNomeCompleto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNomeCompleto.setText("Nome Completo:");

        lbSexo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbSexo.setText("Sexo:");

        cbGenderUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino" }));

        lbEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbEstado.setText("Estado:");

        lbCidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbCidade.setText("Cidade");

        lbEndereco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbEndereco.setText("Endereço:");

        lbBairro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbBairro.setText("Bairro");

        lbNumero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbNumero.setText("Número:");

        lbComplemento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbComplemento.setText("Complemento:");

        btProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/iconfinder_icon-111-search_314478.png"))); // NOI18N
        btProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbComplemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbNomeCompleto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edNomeCompleto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(lbNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbGenderUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbCepUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lbEstado))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbBairro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edEstado)
                            .addComponent(edBairro)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbDtNascimentoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftDatadeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbCpfUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbFoneUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCompleto)
                    .addComponent(edNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDtNascimentoUsuario)
                    .addComponent(jftDatadeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFoneUsuario)
                    .addComponent(jftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCpfUsuario)
                    .addComponent(jftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btProcurar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbSexo)
                        .addComponent(cbGenderUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCepUsuario)
                        .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbEstado)
                        .addComponent(edEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(edCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBairro)
                    .addComponent(edBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(edEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumero))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplemento)
                    .addComponent(edComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 630, 320));

        lbPlanodeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/titidea/images/380567.png"))); // NOI18N
        jPanel1.add(lbPlanodeFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarTelaCadasUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarTelaCadasUsuarioActionPerformed
        FTelaInicial TelaInicial = new FTelaInicial();
        TelaInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarTelaCadasUsuarioActionPerformed

    private void edEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edEmailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edEmailUsuarioActionPerformed

    private void btCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarUsuarioActionPerformed

        
        Usuario u = new Usuario();
        UsuarioDao dao = new UsuarioDao();
        u.setLoginUser(edLoginUsuario.getText());
        u.setPasswordUser(edSenhaUsuario.getText());
        u.setNameUser(edNomeCompleto.getText());
        u.setDateUser(jftDatadeNascimento.getText());
        u.setGenderUser(cbGenderUser.getSelectedIndex());
        u.setCpfUser(jftCPF.getText());
        u.setPhoneUser(jftTelefone.getText());
        u.setEmailUser(edEmailUsuario.getText());
        u.setCepUser(jftCEP.getText());
        u.setCountryUser(edEstado.getText());
        u.setCityUser(edCidade.getText());
        u.setDistrictUser(edBairro.getText());
        u.setAddressUser(edEndereco.getText());
        u.setNumberHouseUser(edNumero.getText());
        u.setComplementHouseUser(edComplemento.getText());
        dao.create(u);
        FTelaInicial TelaInicial = new FTelaInicial();
        TelaInicial.setVisible(true);
        dispose();
                
         
   

    }//GEN-LAST:event_btCadastrarUsuarioActionPerformed

    private void edLoginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edLoginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edLoginUsuarioActionPerformed

    private void jftCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftCEPActionPerformed

    private void edSenhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edSenhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edSenhaUsuarioActionPerformed

    private void btProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcurarActionPerformed
        ViaCEP viacep = new ViaCEP();
        try {
            viacep.buscar(jftCEP.getText());
            edEstado.setText(viacep.getUf());
            edCidade.setText(viacep.getLocalidade());
            edBairro.setText(viacep.getBairro());
            edEndereco.setText(viacep.getLogradouro());
        } catch (ViaCEPException ex) {
            Logger.getLogger(fTelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btProcurarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fTelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fTelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fTelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fTelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new fTelaCadastroUsuario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarUsuario;
    private javax.swing.JButton btProcurar;
    private javax.swing.JButton btVoltarTelaCadasUsuario;
    private javax.swing.JComboBox<String> cbGenderUser;
    private javax.swing.JTextField edBairro;
    private javax.swing.JTextField edCidade;
    private javax.swing.JTextField edComplemento;
    private javax.swing.JTextField edEmailUsuario;
    private javax.swing.JTextField edEndereco;
    private javax.swing.JTextField edEstado;
    private javax.swing.JTextField edLoginUsuario;
    private javax.swing.JTextField edNomeCompleto;
    private javax.swing.JTextField edNumero;
    private javax.swing.JPasswordField edSenhaUsuario;
    private javax.swing.ButtonGroup gpButtonsSexo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField jftCEP;
    private javax.swing.JFormattedTextField jftCPF;
    private javax.swing.JFormattedTextField jftDatadeNascimento;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCepUsuario;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbCpfUsuario;
    private javax.swing.JLabel lbDtNascimentoUsuario;
    private javax.swing.JLabel lbEmailUsuario;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbFoneUsuario;
    private javax.swing.JLabel lbLoginUsuario;
    private javax.swing.JLabel lbNomeCompleto;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbPlanodeFundo;
    private javax.swing.JLabel lbSenhaUsuario;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTituloCadastroUsuario;
    // End of variables declaration//GEN-END:variables
}
